### ISSUE TITLE
Doesn't seem to return all orders by default

### ISSUE THREAD

**Issue by frankhuurman** [alexanderlhsglobal/python-bol-retailer-api#1]
Hi Alexander,

First of all thanks for continuing the development of this PyPI package :) If I get up to speed with it a bit more I wouldn't mind helping out to maintain it.

But for now I've got a question.

When using the example below

```
orderlist = api.orders.list()

for order in orderlist.orders:
    print(order.orderId)
```

I only get my last **sent** order back, not the rest of the orders that have already been sent.

Perhaps it only returns all **open** orders by default? If that's the case then I didn't expect a sent order to be returned instead of an open one(currently have 0 open orders) but perhaps that's Bol.com behavior.

**Comment by alexander-schillemans** [comment]
Hi Frank

Thanks for bringing this to my attention.

By default, it should return all orders (including with shipped and/or cancelled items), fulfilled by the retailer (FBR).

Is it possible that your orders are being fulfilled by Bol (FBB)? These orders will not be returned by default.
See: https://api.bol.com/retailer/public/redoc/v7/retailer.html#operation/get-orders
Package defaults:
- page = 1
- method = FBR
- status = ALL


If you would like to retrieve orders that are being fulfilled by Bol, you can specify the method:

`orderlist = api.orders.list(method='FBB')`

I'm using this wrapper daily and have not seemed to encounter any issues with it yet.

Please let me know if this solves your problem. If not, I'd be happy to look into this.

**Comment by frankhuurman** [comment]
Thanks for the reply!

I think I figured it out. Apparently Bol returned my last 'handled' (not shipped) order when I used status = OPEN(I didn't have any open orders at the time that I tried your library). I'm using fulfilment by retailer(FBR) as well.

Think I just need to dive into the lib some more to figure things out 😄 

Closing ticket for now.
